import type { PromptFramework } from "@stsgs/shared";

export const FRAMEWORKS_DATA: PromptFramework[] = [
  {
    id: "rtf", name: "Role-Task-Format", acronym: "RTF",
    description: "Simple 3-part structure: assign a role, define the task, specify the output format.",
    steps: [
      { label: "Role", description: "Who the AI should act as", required: true, placeholder: "You are a senior TypeScript developer..." },
      { label: "Task", description: "What the AI needs to do", required: true, placeholder: "Write a function that validates emails..." },
      { label: "Format", description: "Desired output format", required: false, placeholder: "Return a TypeScript function with JSDoc..." },
    ],
    bestFor: ["Quick prompts", "Task delegation", "Code generation", "Simple requests", "Beginner prompting"],
    complexity: "simple",
  },
  {
    id: "rise", name: "Role-Input-Steps-Expectation", acronym: "RISE",
    description: "4-step framework for structured task execution with clear expectations and process guidance.",
    steps: [
      { label: "Role", description: "AI persona to adopt", required: true, placeholder: "Act as a data analyst..." },
      { label: "Input", description: "Context or data provided", required: true, placeholder: "Here is the sales data for Q4..." },
      { label: "Steps", description: "Process to follow", required: false, placeholder: "1. Clean data 2. Identify trends 3. Summarize" },
      { label: "Expectation", description: "Expected output quality", required: false, placeholder: "Actionable insights with charts..." },
    ],
    bestFor: ["Data analysis", "Process automation", "Training tutorials", "Quality-controlled output", "Research tasks"],
    complexity: "simple",
  },
  {
    id: "create", name: "Context-Request-Explanation-Action-Tone-Extras", acronym: "CREATE",
    description: "Comprehensive 6-step framework for detailed, nuanced prompts with tone control.",
    steps: [
      { label: "Context", description: "Background information", required: true, placeholder: "We are migrating from REST to GraphQL..." },
      { label: "Request", description: "The main task or question", required: true, placeholder: "Design a schema for user management..." },
      { label: "Explanation", description: "Why this matters", required: false, placeholder: "This ensures type safety across services..." },
      { label: "Action", description: "Specific steps to take", required: false, placeholder: "Define types, resolvers, and mutations..." },
      { label: "Tone", description: "Desired communication style", required: false, placeholder: "Technical and precise..." },
      { label: "Extras", description: "Additional constraints", required: false, placeholder: "Use Apollo Server conventions..." },
    ],
    bestFor: ["Complex documentation", "API design", "Strategic planning", "Content creation", "Technical writing"],
    complexity: "moderate",
  },
  {
    id: "care", name: "Context-Action-Result-Example", acronym: "CARE",
    description: "Simple 4-step framework emphasizing clear results and examples for guidance.",
    steps: [
      { label: "Context", description: "Situation or background", required: true, placeholder: "Our team uses Scrum with 2-week sprints..." },
      { label: "Action", description: "What to do", required: true, placeholder: "Write a sprint retrospective template..." },
      { label: "Result", description: "Expected outcome", required: false, placeholder: "A structured meeting agenda..." },
      { label: "Example", description: "Sample output", required: false, placeholder: "See our last retro summary..." },
    ],
    bestFor: ["Templates", "Standard procedures", "Quick guides", "Onboarding docs", "Meeting frameworks"],
    complexity: "simple",
  },
  {
    id: "trace", name: "Task-Request-Action-Context-Example", acronym: "TRACE",
    description: "5-step framework with example-driven prompting for tasks needing clarity and demonstration.",
    steps: [
      { label: "Task", description: "High-level goal", required: true, placeholder: "Create a CI/CD pipeline..." },
      { label: "Request", description: "Specific ask", required: true, placeholder: "Write GitHub Actions YAML..." },
      { label: "Action", description: "Execution steps", required: false, placeholder: "Lint, test, build, deploy..." },
      { label: "Context", description: "Environment details", required: false, placeholder: "Node.js 20, pnpm monorepo..." },
      { label: "Example", description: "Reference output", required: false, placeholder: "Similar pipeline from repo X..." },
    ],
    bestFor: ["DevOps automation", "Code reviews", "Debugging guides", "Technical tutorials", "Workflow design"],
    complexity: "moderate",
  },
  {
    id: "scope", name: "Specific-Context-Objective-Persona-Execution", acronym: "SCOPE",
    description: "5-step framework combining persona-driven prompting with clear execution strategy.",
    steps: [
      { label: "Specific", description: "Exact requirements", required: true, placeholder: "Build a rate limiter middleware..." },
      { label: "Context", description: "Project environment", required: true, placeholder: "Express.js API with Redis..." },
      { label: "Objective", description: "Goal to achieve", required: true, placeholder: "100 req/min per user limit..." },
      { label: "Persona", description: "AI role", required: false, placeholder: "Senior backend engineer..." },
      { label: "Execution", description: "How to deliver", required: false, placeholder: "Provide code with tests and docs..." },
    ],
    bestFor: ["Feature development", "System design", "Middleware creation", "Architecture tasks", "Project scoping"],
    complexity: "moderate",
  },
  {
    id: "packed", name: "Purpose-Audience-Context-Key info-Emotion-Detail", acronym: "PACKED",
    description: "Rich 6-step framework for audience-aware, emotionally intelligent prompting.",
    steps: [
      { label: "Purpose", description: "Intent of the prompt", required: true, placeholder: "Persuade users to upgrade..." },
      { label: "Audience", description: "Target readers", required: true, placeholder: "Free-tier users of our SaaS..." },
      { label: "Context", description: "Background details", required: true, placeholder: "Launching Pro plan next month..." },
      { label: "Key info", description: "Critical data points", required: false, placeholder: "Pro costs $29/mo, includes X, Y..." },
      { label: "Emotion", description: "Desired emotional tone", required: false, placeholder: "Encouraging and urgent..." },
      { label: "Detail", description: "Level of specificity", required: false, placeholder: "Bullet points, under 200 words..." },
    ],
    bestFor: ["Marketing copy", "User communication", "Persuasive writing", "Email campaigns", "Product launch content"],
    complexity: "moderate",
  },
  {
    id: "stone", name: "Setup-Task-Objective-Notes-Extras", acronym: "STONE",
    description: "Simple 5-step framework with practical setup focus and room for additional notes.",
    steps: [
      { label: "Setup", description: "Prerequisites or config", required: true, placeholder: "PostgreSQL 16, Prisma ORM..." },
      { label: "Task", description: "What to accomplish", required: true, placeholder: "Create a migration script..." },
      { label: "Objective", description: "Success criteria", required: true, placeholder: "Zero-downtime schema change..." },
      { label: "Notes", description: "Additional guidance", required: false, placeholder: "Use soft deletes pattern..." },
      { label: "Extras", description: "Optional additions", required: false, placeholder: "Add rollback script too..." },
    ],
    bestFor: ["Database tasks", "Config management", "Migration scripts", "Setup guides", "Infrastructure work"],
    complexity: "simple",
  },
  {
    id: "co-star", name: "Context-Objective-Style-Tone-Audience-Response", acronym: "CO-STAR",
    description: "Professional 6-step framework with style, tone, and audience targeting for polished output.",
    steps: [
      { label: "Context", description: "Background information", required: true, placeholder: "We are rebranding from Co to Z.ai..." },
      { label: "Objective", description: "What to achieve", required: true, placeholder: "Write a brand announcement..." },
      { label: "Style", description: "Writing style", required: false, placeholder: "Professional yet approachable..." },
      { label: "Tone", description: "Emotional quality", required: false, placeholder: "Confident and forward-looking..." },
      { label: "Audience", description: "Who reads this", required: false, placeholder: "Enterprise clients and partners..." },
      { label: "Response", description: "Output format", required: false, placeholder: "500-word blog post with headers..." },
    ],
    bestFor: ["Brand messaging", "Professional writing", "Executive summaries", "Client proposals", "Corporate comms"],
    complexity: "moderate",
  },
  {
    id: "rag", name: "Retrieval-Augmented Generation Prompt", acronym: "RAG",
    description: "Complex framework for prompts that integrate retrieved documents into generation context.",
    steps: [
      { label: "Retrieval Query", description: "Search query for documents", required: true, placeholder: "Find policies on data retention..." },
      { label: "Context Window", description: "Retrieved document chunks", required: true, placeholder: "[Insert retrieved passages here]..." },
      { label: "Generation Task", description: "What to produce from context", required: true, placeholder: "Summarize key retention rules..." },
      { label: "Citation Style", description: "How to reference sources", required: false, placeholder: "Cite section numbers inline..." },
    ],
    bestFor: ["Knowledge-base QA", "Document summarization", "Legal compliance", "Technical documentation", "Research synthesis"],
    complexity: "complex",
  },
  {
    id: "chain", name: "Multi-Agent Chain Framework", acronym: "CHAIN",
    description: "Complex framework for orchestrating multi-step agent pipelines with handoff coordination.",
    steps: [
      { label: "Pipeline Definition", description: "Agent sequence and roles", required: true, placeholder: "Researcher → Writer → Reviewer → Publisher" },
      { label: "Agent Prompts", description: "Per-agent instructions", required: true, placeholder: "Agent 1: Gather sources. Agent 2: Draft..." },
      { label: "Handoff Format", description: "Inter-agent data contract", required: true, placeholder: "JSON with title, content, sources, status" },
      { label: "Routing Rules", description: "Decision logic for flow", required: false, placeholder: "If score < 7, send back to Writer..." },
      { label: "Aggregation", description: "Final output assembly", required: false, placeholder: "Merge all agent outputs into report..." },
    ],
    bestFor: ["Multi-agent pipelines", "Complex workflows", "Content pipelines", "Automated reviews", "Research reports"],
    complexity: "complex",
  },
];
