import type { PromptTechnique } from "@stsgs/shared";

const TECHNIQUES_DATA: PromptTechnique[] = [
  {
    id: "explicit-instruction",
    name: "Explicit Instruction",
    description: "State exactly what you want with no ambiguity. Removes guesswork for the model.",
    category: "clarity",
    applicableTo: ["json", "markdown", "plain-text", "code", "yaml", "html", "table", "list", "conversation"],
    difficulty: "beginner",
    example: 'Return a JSON object with keys "summary" (string) and "sentiment" (one of positive/negative/neutral).',
  },
  {
    id: "role-assignment",
    name: "Role Assignment",
    description: "Tell the model who it should be. Anchors tone, expertise, and perspective.",
    category: "role-play",
    applicableTo: ["json", "markdown", "plain-text", "code", "html", "yaml", "table", "list", "conversation"],
    difficulty: "beginner",
    example: "You are a senior Kubernetes SRE. Diagnose this pod crash loop in a production cluster.",
  },
  {
    id: "few-shot",
    name: "Few-Shot Examples",
    description: "Provide 2-5 input/output examples so the model infers the pattern you need.",
    category: "reasoning",
    applicableTo: ["json", "markdown", "code", "yaml", "html", "table"],
    difficulty: "intermediate",
    example: 'Q: "Hello world" -> {"lang":"en"}\nQ: "Bonjour le monde" -> {"lang":"fr"}',
  },
  {
    id: "chain-of-thought",
    name: "Chain-of-Thought",
    description: "Ask the model to reason step-by-step before answering. Improves accuracy on complex tasks.",
    category: "chain-of-thought",
    applicableTo: ["json", "markdown", "plain-text", "code"],
    difficulty: "intermediate",
    example: "Think through this step-by-step: first identify the entities, then classify each relationship.",
  },
  {
    id: "structured-output",
    name: "Structured Output",
    description: "Constrain the model to produce output matching a given schema or template format.",
    category: "formatting",
    applicableTo: ["json", "yaml", "html", "table", "code"],
    difficulty: "intermediate",
    example: "Respond with valid JSON matching this schema: {title: string, tags: string[], priority: 1-5}.",
  },
  {
    id: "self-consistency",
    name: "Self-Consistency",
    description: "Sample multiple reasoning paths and take the majority answer. Reduces hallucination.",
    category: "reasoning",
    applicableTo: ["json", "markdown", "plain-text"],
    difficulty: "advanced",
    example: "Solve this math problem using three different methods, then report the most common answer.",
  },
  {
    id: "negative-constraint",
    name: "Negative Constraint",
    description: "Explicitly forbid undesired behaviors or outputs. Prevents common failure modes.",
    category: "constraint",
    applicableTo: ["json", "markdown", "plain-text", "code", "yaml", "html", "table", "list", "conversation"],
    difficulty: "beginner",
    example: "Do NOT include any URLs, email addresses, or external references in your response.",
  },
  {
    id: "token-budget",
    name: "Token Budget",
    description: "Set an explicit length limit so the model stays concise and on-topic.",
    category: "constraint",
    applicableTo: ["json", "markdown", "plain-text", "code", "yaml", "html", "table", "list"],
    difficulty: "beginner",
    example: "Summarize in under 100 words. Do not exceed this limit under any circumstances.",
  },
  {
    id: "adversarial-reviewer",
    name: "Adversarial Reviewer",
    description: "Instruct the model to critique its own output before finalizing. Catches errors early.",
    category: "role-play",
    applicableTo: ["json", "markdown", "code", "plain-text"],
    difficulty: "advanced",
    example: "After drafting, switch roles to a skeptical reviewer and list at least 3 weaknesses.",
  },
  {
    id: "delimiter-pattern",
    name: "Delimiter Pattern",
    description: "Use triple-backticks, XML tags, or other markers to separate input sections clearly.",
    category: "formatting",
    applicableTo: ["json", "markdown", "code", "yaml", "html"],
    difficulty: "beginner",
    example: 'Analyze the text between <<<START>>> and <<<END>>> delimiters below.',
  },
  {
    id: "xml-tag-structure",
    name: "XML Tag Structure",
    description: "Wrap prompt sections in semantic XML tags for clear boundaries and parsing.",
    category: "formatting",
    applicableTo: ["json", "markdown", "code", "yaml", "html", "plain-text"],
    difficulty: "intermediate",
    example: "<context>...</context><instructions>...</instructions><examples>...</examples>",
  },
  {
    id: "meta-prompting",
    name: "Meta-Prompting",
    description: "Ask the model to generate or optimize prompts itself. Useful for prompt engineering.",
    category: "meta",
    applicableTo: ["json", "markdown", "plain-text"],
    difficulty: "advanced",
    example: "Given this task description, generate an optimal prompt that a junior dev could use.",
  },
  {
    id: "prompt-chaining",
    name: "Prompt Chaining",
    description: "Break a complex task into sequential prompts, feeding each output into the next.",
    category: "meta",
    applicableTo: ["json", "markdown", "code", "yaml"],
    difficulty: "advanced",
    example: "Step 1: Extract entities -> Step 2: Classify relationships -> Step 3: Build knowledge graph.",
  },
  {
    id: "plan-and-solve",
    name: "Plan-and-Solve",
    description: "First create an explicit plan, then execute each step. Combines planning with CoT.",
    category: "chain-of-thought",
    applicableTo: ["json", "markdown", "code", "plain-text"],
    difficulty: "intermediate",
    example: "First list the steps needed, then execute each step one at a time with full reasoning.",
  },
  // ---- Architecture patterns (from Hermes Agent analysis) ----
  {
    id: "three-layer-memory",
    name: "3-Layer Memory Architecture",
    description: "Design agent prompts with three distinct memory layers: short-term (current session context), long-term (persistent storage with retrieval), and procedural (skills/knowledge as executable instructions). Each layer serves a different temporal scope and access pattern.",
    category: "architecture",
    applicableTo: ["markdown", "plain-text", "code", "conversation"],
    difficulty: "advanced",
    example: "You have three memory types: (1) This conversation is your short-term memory. (2) Query MEMORY.md for long-term facts. (3) Load relevant skills from /skills/ for procedural knowledge. Always check all three before answering.",
  },
  {
    id: "skill-nudges",
    name: "Skill Self-Improvement Nudges",
    description: "Prompt the agent to proactively save new knowledge as reusable skills after complex tasks. Prevents knowledge loss between sessions and builds a growing procedural memory. Inspired by Hermes Agent's nudge system.",
    category: "architecture",
    applicableTo: ["markdown", "plain-text", "code", "conversation"],
    difficulty: "intermediate",
    example: "After completing a complex task, check if the approach could be reusable. If yes, save it as a skill in /skills/ with trigger words, steps, and examples. This builds your procedural memory for future sessions.",
  },
  {
    id: "mcp-tool-reference",
    name: "MCP Tool Reference Pattern",
    description: "Reference external tools via Model Context Protocol (MCP) in prompts. MCP provides a standardized way to discover, describe, and invoke tools across providers. Use this pattern when designing agents that need extensible tool integration.",
    category: "architecture",
    applicableTo: ["json", "markdown", "code", "yaml"],
    difficulty: "advanced",
    example: "Available tools are served via MCP. Use tool_name and parameters as defined in the MCP schema. Before calling any tool, verify its description matches your intent. Report tool failures with the exact error from the MCP response.",
  },
];

export { TECHNIQUES_DATA };
