import { db } from "@/lib/db";
import { NextResponse } from "next/server";

type Params = { params: Promise<{ id: string }> };

/**
 * GET /api/skills/[id]/export
 * Generates SKILL.md content from a Skill DB record.
 * Returns markdown content as downloadable text.
 */
export async function GET(_request: Request, { params }: Params) {
  try {
    const { id } = await params;
    const skill = await db.skill.findUnique({ where: { id } });
    if (!skill) return NextResponse.json({ error: "Not found" }, { status: 404 });

    const tags: string[] = JSON.parse(skill.tags);
    const inputSchema: Record<string, unknown> = JSON.parse(skill.inputSchema);
    const outputSchema: Record<string, unknown> = JSON.parse(skill.outputSchema);
    const standardIds: string[] = JSON.parse(skill.standardIds);

    // Resolve linked standard names
    const linkedStandards = standardIds.length > 0
      ? await db.standard.findMany({ where: { id: { in: standardIds } }, select: { id: true, name: true } })
      : [];

    const md = generateSkillMd({
      name: skill.name,
      description: skill.description,
      category: skill.category,
      tags,
      code: skill.code,
      tests: skill.tests,
      inputSchema,
      outputSchema,
      standards: linkedStandards.map(s => s.name),
    });

    return new NextResponse(md, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="${skill.name.toLowerCase().replace(/\s+/g, "-")}-skill.md"`,
      },
    });
  } catch (error) {
    console.error("[GET /api/skills/:id/export]", error);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}

function generateSkillMd(ctx: {
  name: string; description: string; category: string; tags: string[];
  code: string; tests: string;
  inputSchema: Record<string, unknown>; outputSchema: Record<string, unknown>;
  standards: string[];
}): string {
  const lines: string[] = [];

  // YAML frontmatter
  lines.push("---");
  lines.push(`name: ${ctx.name.toLowerCase().replace(/\s+/g, "-")}`);
  lines.push("version: 1.0");
  lines.push(`description: >`);
  const descLines = ctx.description.split("\n").filter((l) => l.trim());
  if (descLines.length > 0) {
    for (const dl of descLines) lines.push(`  ${dl.trim()}`);
  } else {
    lines.push(`  ${ctx.category} skill: ${ctx.name}`);
  }
  lines.push("---");
  lines.push("");

  // Title
  lines.push(`# ${ctx.name}`);
  lines.push("");

  // Description
  if (descLines.length > 0) {
    lines.push("## Description");
    lines.push("");
    for (const dl of descLines) lines.push(dl);
    lines.push("");
  }

  // Metadata
  lines.push("## Metadata");
  lines.push("");
  lines.push(`- **Category:** ${ctx.category}`);
  lines.push(`- **Tags:** ${ctx.tags.length > 0 ? ctx.tags.join(", ") : "none"}`);
  if (ctx.standards.length > 0) {
    lines.push(`- **Standards:** ${ctx.standards.join(", ")}`);
  }
  lines.push("");

  // Input Schema
  lines.push("## Input Schema");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(ctx.inputSchema, null, 2));
  lines.push("```");
  lines.push("");

  // Output Schema
  lines.push("## Output Schema");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(ctx.outputSchema, null, 2));
  lines.push("```");
  lines.push("");

  // Code
  if (ctx.code.trim()) {
    lines.push("## Implementation");
    lines.push("");
    lines.push("```");
    lines.push(ctx.code.trim());
    lines.push("```");
    lines.push("");
  }

  // Tests
  if (ctx.tests.trim()) {
    lines.push("## Tests");
    lines.push("");
    lines.push("```");
    lines.push(ctx.tests.trim());
    lines.push("```");
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by 3A Studio Skill Forge");

  return lines.join("\n");
}
